name: Java CI/CD with Maven

on:
 push:
  branches:
   - main

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - uses: actions/setup-java@v2
     with:
      java-version: 8.0.382+5
      distribution: 'adopt'
   - name: Build
     run: mvn clean install
 test:
  runs-on: ubuntu-latest
  needs: build
  steps:
   - uses: actions/checkout@v2
   - uses: actions/setup-java@v2
     with:
      java-version: 8.0.382+5
      distribution: 'adopt'
   - name: Test
     run: mvn test

# deploy:
#  runs-on: ubuntu-latest
#  needs: test
#  steps:
#   - uses: actions/checkout@v2
#   - uses: actions/setup-java@v2
#     with:
#      java-version: 8.0.382+5
#      distribution: 'adopt'
#   - name: Deploy
#     run: |
#      mvn deploy -Dmaven.test.skip=true -DskipTests -Dmaven.username=${{ secrets.MAVEN_USERNAME }} -Dmaven.password=${{ secrets.GITHUB_TOKEN }}
#     env:
#      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
#      MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

