name: Java CI/CD with Maven

on:
 push:
  branches:
   - main

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - uses: actions/setup-java@v2
     with:
      java-version: 8.0.382+5
      distribution: 'adopt'
   - name: Build
     run: mvn clean compile
 test:
  runs-on: ubuntu-latest
  needs: build
  steps:
   - uses: actions/checkout@v2
   - uses: actions/setup-java@v2
     with:
      java-version: 8.0.382+5
      distribution: 'adopt'
   - name: Test
     run: mvn test


